services:
  openwrt1:
    hostname: openwrt1
    labels:
      - attach_host_bridge=yes
      - attach_hwsim_phy=0,1
    build:
      context: ../
      dockerfile: docker/build/Dockerfile
      args:
        BUILD_CONTROLLER: 1
    command: /sbin/init
    volumes:
      - ../umapd/files/umapd.agent.init:/etc/init.d/umap-agent
      - ../umapd/files/umapd.agent.defaults:/etc/uci-defaults/umap-agent
      - ../umapd/files/umapd.controller.init:/etc/init.d/umap-controller
      - ../umapd/files/umapd.controller.defaults:/etc/uci-defaults/umap-controller
      - ../umapd/src/umap:/usr/share/ucode/umap
      - ../umapd/src/umap.uc:/usr/sbin/umapd
      - ../umapd/src/wifi-apply.uc:/usr/libexec/umap/wifi-apply
      - ../umapd/src/wps-connect.uc:/usr/sbin/wps-connect
      - ./build/radio-presets.sh:/etc/uci-defaults/radio-presets.sh
    networks:
      - openwrt_internal
    ports:
      - "1905:80"
    cap_add:
      - NET_ADMIN
    entrypoint: |
      sh -c '
      cat <<EOT > /etc/config/network
      config interface loopback
        option device lo
        option proto static
        option ipaddr 127.0.0.1/8

      config interface lan
        option device eth0
        option proto static
        option ipaddr 192.168.1.1/24

      config interface wan
        option device eth1
        option proto static
        option ipaddr 10.210.54.10/24
        option gateway 10.210.54.1
        option dns 8.8.8.8

      config interface easymesh
        option device easymesh0
        option proto static
        option ipaddr 10.42.0.1/24

      config device
        option type bridge
        option name easymesh0
        option stp 1
        option bridge_empty 1
      EOT
      cat <<EOT >> /etc/config/dhcp
      config dhcp
        option interface easymesh
        option start 100
        option limit 150
        option leasetime 1h
      EOT
      cat <<EOT >> /etc/config/firewall
      config zone
        option name easymesh
        option network easymesh
        option input REJECT
        option output ACCEPT
        option forward REJECT

      config forwarding
        option src easymesh
        option dest wan

      config rule
        option name "easymesh: Allow-DHCP"
        option src easymesh
        option proto udp
        option dest_port 67-68
        option target ACCEPT
        option family ipv4

      config rule
        option name "Allow wan ui access"
        option src wan
        option proto tcp
        option dest_port 80
        option target ACCEPT
      EOT
      mkdir -p /var/lock
      /etc/init.d/umap-controller enable
      /etc/init.d/umap-agent enable
      exec /sbin/init
      '

  openwrt2:
    hostname: openwrt2
    labels:
      - attach_hwsim_phy=2,3
    build:
      context: ../
      dockerfile: docker/build/Dockerfile
    command: /sbin/init
    volumes:
      - ../umapd/files/umapd.agent.init:/etc/init.d/umap-agent
      - ../umapd/files/umapd.agent.defaults:/etc/uci-defaults/umap-agent
      - ../umapd/src/umap:/usr/share/ucode/umap
      - ../umapd/src/umap.uc:/usr/sbin/umapd
      - ../umapd/src/wifi-apply.uc:/usr/libexec/umap/wifi-apply
      - ../umapd/src/wps-connect.uc:/usr/sbin/wps-connect
      - ./build/radio-presets.sh:/etc/uci-defaults/radio-presets.sh
    networks:
      - openwrt_internal
    cap_add:
      - NET_ADMIN
    entrypoint: |
      sh -c '
      cat <<EOT > /etc/config/network
      config interface loopback
        option device lo
        option proto static
        option ipaddr 127.0.0.1/8

      config interface lan
        option device eth0
        option proto static
        option ipaddr 192.168.1.2/24
        #option gateway 192.168.1.1
        #option dns 192.168.1.1
      EOT
      mkdir -p /var/lock
      /etc/init.d/dnsmasq disable
      /etc/init.d/umap-agent enable
      exec /sbin/init
      '

  openwrt3:
    hostname: openwrt3
    labels:
      - attach_hwsim_phy=4,5
    build:
      context: ../
      dockerfile: docker/build/Dockerfile
    command: /sbin/init
    volumes:
      - ../umapd/files/umapd.agent.init:/etc/init.d/umap-agent
      - ../umapd/files/umapd.agent.defaults:/etc/uci-defaults/umap-agent
      - ../umapd/src/umap:/usr/share/ucode/umap
      - ../umapd/src/umap.uc:/usr/sbin/umapd
      - ../umapd/src/wifi-apply.uc:/usr/libexec/umap/wifi-apply
      - ../umapd/src/wps-connect.uc:/usr/sbin/wps-connect
      - ./build/radio-presets.sh:/etc/uci-defaults/radio-presets.sh
    networks:
      - openwrt_internal
    cap_add:
      - NET_ADMIN
    entrypoint: |
      sh -c '
      cat <<EOT > /etc/config/network
      config interface loopback
        option device lo
        option proto static
        option ipaddr 127.0.0.1/8

      config interface lan
        option device eth0
        option proto static
        option ipaddr 192.168.1.3/24
        #option gateway 192.168.1.1
        #option dns 192.168.1.15
      EOT
      mkdir -p /var/lock
      /etc/init.d/dnsmasq disable
      /etc/init.d/umap-agent enable
      exec /sbin/init
      '

  connect-host-network:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    depends_on:
      - openwrt1
    pid: host
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: |
      sh -c '
      set -x
      apk update
      apk add iw

      max_phy_number=$$(
        docker ps -f label=attach_hwsim_phy -q | \
          xargs docker inspect -f "{{.Config.Labels.attach_hwsim_phy}}" | \
          tr "," "\n" | sort -nru | head -n1
      )

      rmmod mac80211_hwsim
      find /lib/modules/$$(uname -r) -name "mac80211_hwsim.ko*" | xargs -r -I"{}" insmod {} radios=$$((max_phy_number + 1))

      curr_phy_number=0
      for phy in /sys/devices/virtual/mac80211_hwsim/hwsim*/ieee80211/phy*; do
        iw phy "$$(basename "$$phy")" set name "wifi$$curr_phy_number"

        docker ps -f "label=attach_hwsim_phy" -q | \
          xargs -r -I"{}" docker inspect -f "{{.State.Pid}} ,{{.Config.Labels.attach_hwsim_phy}}," {} | \
          while read pid phys; do
            case "$$phys" in *",$$curr_phy_number,"*)
              iw phy "wifi$$curr_phy_number" set netns "$$pid"
            esac
          done

        curr_phy_number=$$((curr_phy_number + 1))
      done

      docker ps -f label=attach_host_bridge=yes -q | xargs -I"{}" docker network connect bridge {}
      '

networks:
  openwrt_internal:
    driver: bridge
